# Generated by Django 6.0.3 on 2026-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Користувач з такою поштою вже існує.'}, max_length=254, unique=True, verbose_name='Email адреса'),
        ),
    ]
