# Збільшуємо максимальну довжину рядка для зручності
line-length = 120

# Ігноруємо системні файли та міграції бази даних
exclude = [
    ".git",
    "venv",
    "__pycache__",
    "**/migrations/*",
    "manage.py",
]

[lint]
# Вмикаємо перевірки: E (стиль PEP 8), F (помилки логіки/імпортів), I (сортування імпортів)
select = ["E", "F", "I"]
ignore = []

# Дозволяємо невикористані змінні, якщо вони починаються з підкреслення (наприклад, _var)
dummy-variable-rgx = "^_$"