# Generated by Django 6.0.3 on 2026-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('mal_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID з Jikan API')),
                ('description', models.TextField(verbose_name='Опис')),
                ('poster', models.URLField(max_length=500, verbose_name='URL постера')),
                ('genres', models.CharField(db_index=True, max_length=255, verbose_name='Жанри')),
                ('year', models.CharField(max_length=4, verbose_name='Рік випуску')),
                ('episodes', models.CharField(max_length=50, verbose_name='Кількість епізодів')),
                ('studio', models.CharField(max_length=255, verbose_name='Студія')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус')),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='Загальний рейтинг')),
                ('user_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Ваша оцінка')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В улюблених')),
                ('in_watchlist', models.BooleanField(default=False, verbose_name='Переглянуто')),
                ('planned', models.BooleanField(default=False, verbose_name='Планую подивитись')),
                ('is_added_by_user', models.BooleanField(default=False, verbose_name='Додано користувачем самостійно')),
            ],
            options={
                'verbose_name': 'Аніме',
                'verbose_name_plural': 'Аніме',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='AnimeCache',
            fields=[
                ('anime_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(verbose_name='Дані з API')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кеш аніме',
                'verbose_name_plural': 'Кеш аніме',
            },
        ),
    ]
