# Generated by Django 6.0.3 on 2026-05-05 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCache',
            fields=[
                ('anime_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(verbose_name='Дані з API')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кеш аніме',
                'verbose_name_plural': 'Кеш аніме',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anihub_id', models.IntegerField(unique=True, verbose_name='ID з AniHub')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('title_ukrainian', models.CharField(db_index=True, max_length=255, verbose_name='Українська назва')),
                ('mal_id', models.IntegerField(blank=True, null=True, verbose_name='ID з MyAnimeList')),
                ('anilist_id', models.IntegerField(blank=True, null=True, verbose_name='ID з AniList')),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID з IMDb')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('poster', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL постера')),
                ('genres', models.JSONField(default=list, verbose_name='Жанри')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Рік випуску')),
                ('episodes_count', models.IntegerField(blank=True, null=True, verbose_name='Кількість епізодів')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус')),
                ('has_ukrainian_dub', models.BooleanField(default=False, verbose_name='Є український дубляж')),
                ('dubbing_studios', models.JSONField(default=list, verbose_name='Студії озвучення')),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=4, verbose_name='Загальний рейтинг')),
                ('user_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Ваша оцінка')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В улюблених')),
                ('is_watching', models.BooleanField(default=False, verbose_name='Дивлюся зараз')),
                ('in_watchlist', models.BooleanField(default=False, verbose_name='Переглянуто')),
                ('planned', models.BooleanField(default=False, verbose_name='Планую подивитись')),
                ('is_added_by_user', models.BooleanField(default=False, verbose_name='Додано користувачем самостійно')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Аніме',
                'verbose_name_plural': 'Аніме',
                'ordering': ['-rating'],
            },
        ),
    ]
