# Generated by Django 6.0.3 on 2026-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('poster', models.URLField(max_length=500, verbose_name='URL постера')),
                ('description', models.TextField(verbose_name='Опис')),
                ('genres', models.CharField(max_length=255, verbose_name='Жанри')),
                ('year', models.CharField(max_length=4, verbose_name='Рік випуску')),
                ('episodes', models.CharField(max_length=50, verbose_name='Кількість епізодів')),
                ('studio', models.CharField(max_length=255, verbose_name='Студія')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В улюблених')),
                ('in_watchlist', models.BooleanField(default=False, verbose_name='Переглянуто')),
            ],
            options={
                'verbose_name': 'Аніме',
                'verbose_name_plural': 'Аніме',
                'ordering': ['-rating'],
            },
        ),
    ]
