# Generated by Django 6.0.3 on 2026-05-10 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anihub_id',
            field=models.IntegerField(verbose_name='ID з AniHub'),
        ),
        migrations.AlterUniqueTogether(
            name='anime',
            unique_together={('owner', 'anihub_id')},
        ),
    ]
