# Generated by Django 6.0.3 on 2026-03-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_added_by_user',
            field=models.BooleanField(default=False, verbose_name='Додано користувачем самостійно'),
        ),
        migrations.AddField(
            model_name='anime',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='anime',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Ваша оцінка'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Загальний рейтинг'),
        ),
    ]
