# Generated by Django 6.0.3 on 2026-03-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0002_anime_is_added_by_user_anime_owner_anime_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Жанри'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='Загальний рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Назва'),
        ),
    ]
