# Generated by Django 6.0.3 on 2026-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_watching',
            field=models.BooleanField(default=False, verbose_name='Дивлюся зараз'),
        ),
    ]
