# Generated by Django 6.0.3 on 2026-04-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0003_alter_anime_genres_alter_anime_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCache',
            fields=[
                ('anime_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(verbose_name='Дані з API')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кеш аніме',
                'verbose_name_plural': 'Кеш аніме',
            },
        ),
    ]
