# Generated by Django 6.0.3 on 2026-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0004_animecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='planned',
            field=models.BooleanField(default=False, verbose_name='Планую подивитись'),
        ),
    ]
