# Generated by Django 6.0.3 on 2026-04-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0005_anime_planned'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID з Jikan API'),
        ),
    ]
